[tool.poetry]
name = "ana-backend"
version = "0.1.0"
description = ""
authors = ["LadySeven"]

[tool.poetry.dependencies]
python = "3.10.*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
